### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 187185537** [kimsunkyung/SCA_MTL#1]
is:issue is:open Output channels from the backbone network are [18,36,72,144],but in common_config,the channels from the backbone network are [36,72,144,288],So the code displays an error in decoder network .Which channel number should be used?

**Comment by kimsunkyung** [comment]
Oh sorry, [18,36,72,144] is right. I modified common_config code.

**Comment by kimsunkyung** [comment]
> Oh sorry, [18,36,72,144] is right. I modified common_config code.

**Comment by 187185537** [comment]
Hello, sorry to bother you. I wonder how ATRC you reproduce the results. The results I reproduced were much worse than in the original paper.

**Comment by kimsunkyung** [comment]
> Hello, sorry to bother you. I wonder how ATRC you reproduce the results. The results I reproduced were much worse than in the original paper.

After training for 2-3 tasks using the code provided by ATRC github, validation was carried out.

**Comment by 187185537** [comment]
But I used the author's github source code to reproduce the single-task semantic segmentation Miou performance is as high as 62.37, did you not change the author source code?
Sorry, I don't know why the results are so different.

**Comment by kimsunkyung** [comment]
> But I used the author's github source code to reproduce the single-task semantic segmentation Miou performance is as high as 62.37, did you not change the author source code? Sorry, I don't know why the results are so different.

The performance of single-task semantic segmentation was evaluated by referring to MTINet's code.

**Comment by 187185537** [comment]
Multitasking　Do you run 55.49 with the source code of the ATRC author? But my reproduction using the author's source code is 62.37．The gap is a bit big．

**Comment by kimsunkyung** [comment]
> Multitasking　Do you run 55.49 with the source code of the ATRC author? But my reproduction using the author's source code is 62.37．The gap is a bit big．

Yes, I run 55.49 with the source code of the ATRC author. But you said that you got the 62.37 using the author's code,so  I will run again and check about it. Thank you.

**Comment by kimsunkyung** [comment]
> Multitasking　Do you run 55.49 with the source code of the ATRC author? But my reproduction using the author's source code is 62.37．The gap is a bit big．

And I use MTINet dataset, I didn't download the ATRC github dataset.
